services:
  - type: web
    name: WEB-III-Exercicio-II-main
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py create_admin
    startCommand: gunicorn projeto.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: sua-chave-secreta-aqui